version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
      - mariadb
    environment:
      - NODE_ENV=development
      - API_URL=http://api:4000

  admin:
    build:
      context: ..
      dockerfile: docker/admin.Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - api
      - mariadb
    environment:
      - NODE_ENV=development
      - API_URL=http://api:4000

  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mariadb
    environment:
      - NODE_ENV=development
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=blockchain_db

  mariadb:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=blockchain_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
